#!/bin/bash

sed 's/[ąęśźćżółń]//g' $1 | sed 's/\?//g' | sed 's/\([a-zA-Z]\) /\1/g' | sed $'s/\//\\n/g' | sed '/^$/d' | sed 's/^\(.*\)$/(\1) \& /g' | sed '$ s/ \& //'| tr '\n' ' ' | sed 's/<>/ sometime /g' | sed 's/\[\]/ always /g'
